# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-12-13 05:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('event_type', models.CharField(max_length=40)),
                ('event_ts', models.DateTimeField()),
                ('event_ts_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('geo_lat', models.FloatField()),
                ('geo_long', models.FloatField()),
                ('altitude', models.FloatField()),
                ('vert_accuracy', models.FloatField()),
                ('horiz_accuracy', models.FloatField()),
                ('heading', models.CharField(max_length=20)),
                ('speed', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Trips',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('start_time', models.DateTimeField()),
                ('start_time_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_time', models.DateTimeField()),
                ('end_time_local', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration', models.CharField(max_length=5, null=True)),
                ('distance', models.CharField(max_length=12)),
                ('score', models.CharField(max_length=8)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(blank=True, max_length=5, null=True, unique=True)),
                ('company_id', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=64, unique=True)),
                ('password', models.CharField(default='abcd@1234', max_length=20)),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_track.Role')),
            ],
        ),
        migrations.AddField(
            model_name='trips',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_track.Users'),
        ),
        migrations.AddField(
            model_name='events',
            name='trip_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_track.Trips'),
        ),
    ]
